name: Generate wra-frontend package

on:
  push:
    paths:
      - 'wra_frontend/**'
    branches:
      - main
  workflow_dispatch:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_TOKEN: ${{ secrets.USER_TOKEN }}
  USER_USERNAME: ${{ secrets.USER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup git
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_USERNAME}"
        git remote set-url origin https://${USER_USERNAME}:${USER_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout main

    - name: Make init
      run: make init

    - name: Build package
      run: make package

    - name: Commit package
      run: make commit-package

